DROP TABLE IF EXISTS "UserAccountCard" CASCADE;
DROP TABLE IF EXISTS "UserCard" CASCADE;
DROP TABLE IF EXISTS "UserAccount" CASCADE;
DROP TABLE IF EXISTS "SecureVaultRecord" CASCADE;
DROP TYPE IF EXISTS "SecureRecordType";
