DROP TABLE IF EXISTS "CardCredential" CASCADE;
DROP TABLE IF EXISTS "BankAccountCredential" CASCADE;
DROP TABLE IF EXISTS "Card" CASCADE;
DROP TABLE IF EXISTS "CardType" CASCADE;
DROP TABLE IF EXISTS "Bank" CASCADE;
